#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

password=$YNH_APP_ARG_PASSWORD
ynh_app_setting_set --key=password --value="$password"

#=================================================
# FIND AND OPEN A PORT
#=================================================
ynh_script_progression "Configuring firewall..."

# Reserve UDP Port range 49152:65535
ynh_hide_warnings yunohost firewall allow UDP -4 49152:65535

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir/build"
ynh_setup_source --dest_dir="$install_dir/build_ldap" --source_id="ldap"

mkdir -p "$install_dir/live/data"
mkdir -p "$install_dir/live_ldap/data"

cp -r "$install_dir/build/static/" "$install_dir/live/"
ynh_replace --match="<div class=\"galene-header\">Galène</div>" --replace="<div class=\"galene-header\" onclick=\"location.href=window.location.origin\" style=\"cursor:pointer\">Galène</div>" --file="$install_dir/live/static/galene.html"

chmod -R o-rwx "$install_dir"
chown -R $app:$app "$install_dir"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building $app..."

ynh_go_install

pushd $install_dir/build/galenectl/
	ynh_hide_warnings ynh_exec_as_app CGO_ENABLED=0 go build -o $install_dir/
popd

pushd $install_dir/build/
	ynh_hide_warnings ynh_exec_as_app CGO_ENABLED=0 go build -ldflags='-s -w' -o $install_dir/live/
popd

pushd $install_dir/build_ldap/
	ynh_hide_warnings ynh_exec_as_app CGO_ENABLED=0 go build -ldflags='-s -w' -o $install_dir/live_ldap/
popd

ynh_go_remove
ynh_safe_rm "$install_dir/build/"
ynh_safe_rm "$install_dir/build_ldap/"
ynh_safe_rm "$install_dir/.cache/"
ynh_safe_rm "$install_dir/go/"
ynh_safe_rm "$install_dir/.go-version"

chmod +x "$install_dir/galenectl"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

password_hash=$(HOME=$install_dir $install_dir/galenectl hash-password -password "$password")
ynh_app_setting_set --key=password_hash --value="$password_hash"

# Configure Galène
ynh_config_add --template="config.json" --destination="$install_dir/live/data/config.json"

# Configure galenectl
ynh_config_add --template="galenectl.json" --destination="$install_dir/live/data/galenectl.json"

# Configure Galène LDAP
key=$(jose jwk gen -i '{"kty":"oct","alg":"HS256"}')
ynh_app_setting_set --key=key --value="$key"
ynh_config_add --template="galene-ldap.json" --destination="$install_dir/live_ldap/data/galene-ldap.json"

# Create a group name config
ynh_config_add --template="groupname.json" --destination="$data_dir/groups/$group_name.json"

# Create a group name authenticated on LDAP
ynh_config_add --template="groupname-ldap.json" --destination="$data_dir/groups/YunoHost_Users.json"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

public_ip4="$(curl -s https://ip.yunohost.org)" || true

ynh_config_add_nginx

ynh_config_add_systemd
ynh_config_add_systemd --service=${app}_ldap --template="ldap.service"

yunohost service add $app --description="Videoconferencing server" --needs_exposed_ports="$port_turn"
yunohost service add ${app}_ldap --description="LDAP integration for the videoconferencing server"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd"
ynh_systemctl --service=${app}_ldap --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
