#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status $app >/dev/null
then
	ynh_script_progression "Removing $app service integration..."
	yunohost service remove $app
fi
# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status ${app}_ldap >/dev/null
then
	ynh_script_progression "Removing ${app}_ldap service integration..."
	yunohost service remove ${app}_ldap
fi

# Remove the dedicated systemd config
ynh_config_remove_systemd
ynh_config_remove_systemd${app}_ldap

# Remove the dedicated NGINX config
ynh_config_remove_nginx

#=================================================
# CLOSE A PORT
#=================================================

if yunohost firewall list | grep -q "\- 49152:65535"
then
	ynh_script_progression "Closing UDP ports..."
	ynh_hide_warnings yunohost firewall disallow UDP 49152:65535
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
